config/routes.rb
Radiant::Engine.routes.draw do
  namespace :admin do
    resources :pages do
      resources :children, controller: 'pages'
      member do
        get :remove
        post :preview
        put :preview
      end
    end
    resources :layouts do
      member do
        get :remove
      end
    end
    resources :users do
      member do
        get :remove
      end
    end

    resource :preferences
    resource :configuration
    resources :extensions,  only: :index
    resources :page_parts,  only: :create
    resources :page_fields, only: :create
    get 'reference/:type(.:format)' => 'radiant/references#show', as: :reference
  end

  get 'admin' => 'admin/welcome#index', as: :admin
  get 'admin/welcome' => 'admin/welcome#index', as: :welcome
  match 'admin/login' => 'admin/welcome#login', as: :login, via: [:get, :post]
  get 'admin/logout' => 'admin/welcome#logout', as: :logout

  root to: 'site#show_page'

  get 'error/404' => 'site#not_found', as: :not_found
  get 'error/500' => 'site#error', as: :error

  # main catch-all route
  get '*url' => 'site#show_page'
end

app/controllers/radiant/admin/configurations_controller.rb
module Radiant
  class Admin::ConfigurationsController < ::Radiant::AdminController

    # Admin::ConfigurationController handles the batch-updating of Radiant::Config entries.
    # It accepts any set of config name-value pairs but is accessible only to administrators.
    # Note that configuration is routed as a singular resource so we only deal with show/edit/update
    # and the show and edit views determine what set of config values is shown and made editable.

    before_filter :initialize_detail

    only_allow_access_to :edit, :update,
      when: [:admin],
      denied_url: { controller: 'admin/configuration', action: 'show' },
      denied_message: 'You must have admin privileges to edit site configuration.'

    def show
      @user = current_user
      render
    end

    def edit
      render
    end

    def update
      if params[:config]
        begin
          Radiant.detail.transaction do
            params["config"].each_pair do |key, value|
              @editable_detail[key] = Radiant::Config.find_or_create_by(key: key)
              @editable_detail[key].value = value      # validation sets errors on @editable_config['key'] that the helper methods will pick up
            end
            redirect_to action: :show
          end
        rescue ActiveRecord::RecordInvalid => e
          flash[:error] = "Configuration error: please check the form"
          render action: :edit
        rescue Radiant::Config::ConfigError => e
          flash[:error] = "Configuration error: #{e}"
          render action: :edit
        end
      end
    end

  protected

    def initialize_detail
      @editable_detail = {}
    end

  end
end

app/helpers/radiant/admin/configurations_helper.rb
module Radiant::Admin::ConfigurationsHelper
  # Defines helper methods for use in the admin interface when displaying or editing configuration.

  # Renders the setting as label and value:
  #
  #   show_config("admin.title")
  #   => <label for="admin_title">Admin title<label><span id="admin_title">Radiant CMS</span>
  #
  def show_config(key, options={})
    setting = setting_for(key)
    setting.valid?
    domkey = key.gsub(/\W/, '_')
    html = ""
    html << content_tag(:label, t("config.#{key}").titlecase, for: domkey)
    if setting.boolean?
      value = setting.checked? ? t('yes') : t('no')
      html << content_tag(:span, value, id: domkey, class: "#{value} #{options[:class]}")
    else
      value = setting.selected_value || setting.value
      html << content_tag(:span, value, id: domkey, class: options[:class])
    end
    html << content_tag(:span, " #{t("units.#{setting.units}")}", class: 'units') if setting.units
    html << content_tag(:span, " #{t('warning')}: #{[setting.errors.messages[:value]].flatten.first}", class: 'warning') if setting.errors.messages[:value]
    html.html_safe
  end

  # Renders the setting as label and appropriate input field:
  #
  #   edit_setting("admin.title")
  #   => <label for="admin_title">Admin title<label><input type="text" name="config['admin.title']" id="admin_title" value="Radiant CMS" />
  #
  #   edit_config("defaults.page.status")
  #   =>
  #   <label for="defaults_page_status">Default page status<label>
  #   <select type="text" name="config['defaults.page.status']" id="defaults_page_status">
  #     <option value="Draft">Draft</option>
  #     ...
  #   </select>
  #
  #   edit_setting("user.allow_password_reset?")
  #   => <label for="user_allow_password_reset_">Admin title<label><input type="checkbox" name="config['user.allow_password_reset?']" id="user_allow_password_reset_" value="1" checked="checked" />
  #
  def edit_config(key, options={})
    setting = setting_for(key)
    domkey = key.gsub(/\W/, '_')
    name = "config[#{key}]"
    title = t("config.#{key}").titlecase
    title << content_tag(:span, " (#{t("units.#{setting.units}")})", class: 'units') if setting.units
    value = params[key.to_sym].nil? ? setting.value : params[key.to_sym]
    html = ""
    if setting.boolean?
      html << hidden_field_tag(name, 0)
      html << check_box_tag(name, 1, value, class: 'setting', id: domkey)
      html << content_tag(:label, title, class: 'checkbox', for: domkey)
    elsif setting.selector?
      html << content_tag(:label, title, for: domkey)
      html << select_tag(name, options_for_select(setting.definition.selection, value), class: 'setting', id: domkey)
    else
      html << content_tag(:label, title, for: domkey)
      html << text_field_tag(name, value, class: 'textbox', id: domkey)
    end
    if setting.errors.messages[:value]
      html << content_tag(:span, [setting.errors.messages[:value]].flatten.first, class: 'error')
      html = content_tag(:span, html, class: "error-with-field")
    end
    html.html_safe
  end

  def setting_for(key)
    @editable_config ||= {}    # normally initialized in Admin::ConfigurationController
    @editable_config[key] ||= Radiant.detail.find_or_create_by(key: key)
  end

  def definition_for(key)
    if setting = setting_for(key)
      setting.definition
    end
  end

end

app/views/radiant/admin/configurations/edit.html.haml
- body_classes << "reversed"
- @selected = :general

- render_region :main do |main|
  - main.edit_header do
    %h1 Configuration

  - main.edit_form do
    = form_for :config, :url => admin_configuration_url, :html => {"data-onsubmit_status"=>"Saving changes&#8230;", :method => :put} do |f|
      = render_region :form_top
      - render_region :form do |form|
        - form.edit_site do
          %fieldset
            %h3 Site
            - Radiant.detail.site_settings.each do |site_setting|
              %p
                = edit_config site_setting

        - form.edit_defaults do
          %fieldset
            %h3 Defaults
            - Radiant.detail.default_settings.each do |default_setting|
              %p
                = edit_config default_setting

        - form.edit_users do
          / %fieldset
          /   %h3 Passwords
          /   - Radiant.detail.user_settings.each do |user_setting|
          /     %p
          /       = edit_config user_setting

      - render_region :form_bottom do |form_bottom|
        - form_bottom.edit_buttons do
          .buttons
            %input.button{:type=>"submit", :value=>"Save Changes"}/
            or
            = link_to "Cancel", admin_configuration_url

app/views/radiant/admin/configurations/show.html.haml
- body_classes << "reversed"

#preferences.box
  - render_region :user do |user|
    - user.preferences do
      %h3
        .actions
          = button_to t("edit_preferences"), "/admin/preferences", :method => :get
        = t('personal_preferences')
      = image_tag(gravatar_url(@user.email, :size=>"64px"), :class=>"avatar", :width=>64, :height=>64, :alt=>"")
      %p.ruled
        %label
          = t('name')
        %span
          = current_user.name
      %p.ruled
        %label
          = t('email_address')
        %span.uri
          = current_user.email
      %p.ruled
        %label
          = t('login')
        %span
          = current_user.login
      %p.ruled
        %label
          = t('password')
        %big &bull;&bull;&bull;&bull;&bull;
      %p.ruled
        %label
          = t('language')
        %span
          = current_user.locale

#config.box
  - render_region :config do |config|
    - config.site do
      %h3
        - if admin?
          .actions
            = button_to t("edit_configuration"), edit_admin_configuration_url, :method => :get
        Configuration
      - Radiant.detail.site_settings.each do |site_setting|
        %p.ruled
          = show_config site_setting, :class => (site_setting =~ /host$/ ? 'uri' : nil)

    - config.defaults do
      %h4 Defaults
      - Radiant.detail.default_settings.each do |default_setting|
        %p.ruled
          = show_config default_setting

    - config.users do
      %h4 Passwords
      - Radiant.detail.user_settings.each do |user_setting|
        %p.ruled
          = show_config user_setting