config/routes.rb
Radiant::Engine.routes.draw do
  namespace :admin do
    resources :pages do
      resources :children, controller: 'pages'
      member do
        get :remove
        post :preview
        put :preview
      end
    end
    resources :layouts do
      member do
        get :remove
      end
    end
    resources :users do
      member do
        get :remove
      end
    end

    resource :preferences
    resource :configuration
    resources :extensions,  only: :index
    resources :page_parts,  only: :create
    resources :page_fields, only: :create
    get 'reference/:type(.:format)' => 'radiant/references#show', as: :reference
  end

  get 'admin' => 'admin/welcome#index', as: :admin
  get 'admin/welcome' => 'admin/welcome#index', as: :welcome
  match 'admin/login' => 'admin/welcome#login', as: :login, via: [:get, :post]
  get 'admin/logout' => 'admin/welcome#logout', as: :logout

  root to: 'site#show_page'

  get 'error/404' => 'site#not_found', as: :not_found
  get 'error/500' => 'site#error', as: :error

  # main catch-all route
  get '*url' => 'site#show_page'
end

app/models/layout.rb
class Layout < ActiveRecord::Base
  self.table_name = "layouts"
  attr_accessible :lock_version, :name, :content_type, :content
  # Default Order
  default_scope { order("name") }

  # Associations
  has_many :pages
  belongs_to :created_by, class_name: 'User'
  belongs_to :updated_by, class_name: 'User'

  # Validations
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_length_of :name, maximum: 100
end

app/controllers/radiant/admin/layouts_controller.rb
module Radiant
  class Admin::LayoutsController < ::Radiant::Admin::ResourceController
    paginate_models
    only_allow_access_to :index, :show, :new, :create, :edit, :update, :remove, :destroy,
      when: [:designer, :admin],
      denied_url: { controller: 'admin/pages', action: 'index' },
      denied_message: 'You must have designer privileges to perform this action.'

  end
end

app/helpers/radiant/admin/layouts_helper.rb
module Radiant::Admin::LayoutsHelper
  def layout_edit_javascripts
    <<-CODE
    var tagReferenceWindows = {};
    function loadTagReference() {
      var pageType = 'Page';
      if (!tagReferenceWindows[pageType])
        tagReferenceWindows[pageType] = new Popup.AjaxWindow("#{admin_reference_path('tags')}?class_name=" + encodeURIComponent(pageType), {reload: false});
      var window = tagReferenceWindows[pageType];
      if('Page' != pageType) {
        $('tag_reference_link').highlight();
        window.show();
      } else {
        window.toggle();
      }
      lastPageType = pageType;
      return false;
    }
    CODE
  end
end

app/views/radiant/admin/layouts/_form.html.haml
= form_for [:admin, @layout], :html => {'data-onsubmit_status' => onsubmit_status(@layout)} do |f|
  = f.hidden_field :lock_version
  = render_region :form_top, :locals => {:f => f}
  .form_area
    - render_region :form, :locals => {:f => f} do |form|
      - form.edit_title do
        %p.title
          = f.label :name, t('name')
          = f.text_field :name, :maxlength => 100, :class => "textbox"
      - form.edit_extended_metadata do
        .drawer
          .drawer_contents#attributes
            %table.fieldset
              %tr
                %th.label= f.label :content_type, t('content_type')
                %td.field= f.text_field :content_type, :maxlength => 40, :class => "textbox"
              = render_region :extended_metadata, :locals => {:f => f}
          .drawer_handle
            %a.toggle{:href=>'#attributes', :rel=>"toggle[attributes]", :class=>"#{(meta_errors? ? 'less' : 'more')}"}= meta_label
      - form.edit_content do
        %p.content
          = f.label :layout_content, "Body"
          ~ f.text_area :content, :size => "40x20", :style => "width: 100%", :class => "textarea large"
  = javascript_tag "$('layout_name').activate()"
  - render_region :form_bottom, :locals => {:f => f} do |form_bottom|
    - form_bottom.reference_links do
      %p
        %span.reference_links
          Reference:
          %span{:id => "tag_reference_link"}
            = link_to_function t('available_tags'), "loadTagReference('Page');"
    - form_bottom.edit_buttons do
      .buttons
        = save_model_button @layout
        = save_model_and_continue_editing_button @layout
        = t('or') 
        = link_to t('cancel'), admin_layouts_url
    - form_bottom.edit_timestamp do
      = updated_stamp @layout

app/views/radiant/admin/layouts/edit.html.haml
- @page_title = @layout.name + ' ' + t('layout') + ' - ' + default_page_title

- render_region :main do |main|
  - main.edit_header do
    %h1= t('edit_layout')       
  - main.edit_form do
    = render :partial => 'form'

- content_for 'page_scripts', layout_edit_javascripts

app/views/radiant/admin/layouts/index.html.haml
- @page_title = t('layouts') + ' - ' + default_page_title

.outset
  = render_region :top
  %table.index#layouts
    %thead
      %tr
        - render_region :thead do |thead|
          - thead.title_header do
            %th.name
              = t('layout')
          - thead.actions_header do
            %th.actions{:style=>"width:9em"}
              = t('modify')
    %tbody
      - if @layouts.any?
        - @layouts.each do |layout|
          %tr[layout]
            - render_region :tbody, :locals => {:layout => layout} do |tbody|
              - tbody.title_cell do
                %td.name
                  = link_to image('layout', :alt => '') + ' ' + layout.name, edit_admin_layout_url(layout)
              - tbody.actions_cell do
                %td.actions
                  = link_to image('minus') + ' ' + t('remove'), remove_admin_layout_url(layout), :class => "action"
      - else
        %tr
          %td.empty{:colspan => admin.layout.index.tbody.length}= t('no_layouts')

- render_region :bottom do |bottom|
  - bottom.new_button do
    #actions
      = pagination_for(@layouts)
      %ul
        %li= link_to image('plus') + " " + t('new_layout'), new_admin_layout_url, :class => 'action_button'

app/views/radiant/admin/layouts/new.html.haml
- render_region :main do |main|
  - main.edit_header do
    %h1= t('new_layout')
  - main.edit_form do
    = render :partial => 'form'

- content_for 'page_scripts', layout_edit_javascripts

app/views/radiant/admin/layouts/remove.html.haml
%h1= t('remove_layout')

%p= t('text.layouts.remove_warning')

%table.index#layouts
  %tbody
    %tr.node.level_1
      %td.layout
        = image('layout', :alt => '')
        = h @layout.name

- form_for [:admin, @layout], :html => { :method => 'delete', 'data-onsubmit_status'=>"Removing layout&#8230;" } do
  .buttons
    %input.button{:type => "submit", :value => t('delete_layout')  }/
    = t('or')
    = link_to t('cancel'), admin_layouts_url