config/routes.rb
Radiant::Engine.routes.draw do
  namespace :admin do
    resources :pages do
      resources :children, controller: 'pages'
      member do
        get :remove
        post :preview
        put :preview
      end
    end
    resources :layouts do
      member do
        get :remove
      end
    end
    resources :users do
      member do
        get :remove
      end
    end

    resource :preferences
    resource :configuration
    resources :extensions,  only: :index
    resources :page_parts,  only: :create
    resources :page_fields, only: :create
    get 'reference/:type(.:format)' => 'radiant/references#show', as: :reference
  end

  get 'admin' => 'admin/welcome#index', as: :admin
  get 'admin/welcome' => 'admin/welcome#index', as: :welcome
  match 'admin/login' => 'admin/welcome#login', as: :login, via: [:get, :post]
  get 'admin/logout' => 'admin/welcome#logout', as: :logout

  root to: 'site#show_page'

  get 'error/404' => 'site#not_found', as: :not_found
  get 'error/500' => 'site#error', as: :error

  # main catch-all route
  get '*url' => 'site#show_page'
end

app/controllers/radiant/admin/preferences_controller.rb
require 'radiant/available_locales'

module Radiant
  class Admin::PreferencesController < ::Radiant::AdminController
    before_filter :load_user

    def initialize
      super
      @controller_name = 'user'
      @template_name = 'preferences'
    end

    def show
      set_standard_body_style
      render :edit
    end

    def edit
      render
    end

    def update
      if valid_params?
        if @user.update_attributes(params[:user])
          redirect_to admin_configuration_path
        else
          flash[:error] = t('preferences_controller.error_updating')
          render :edit
        end
      else
        announce_bad_data
        render :edit
      end
    end

    private

    def load_user
      @user = current_user
    end

    def valid_params?
      hash = (params[:user] || {}).symbolize_keys
      (hash.keys - User.unprotected_attributes).size == 0
    end

    def announce_bad_data
      flash[:error] = 'Bad form data.'
    end
  end
end

app/helpers/radiant/admin/preferences_helper.rb
module Radiant::Admin::PreferencesHelper

end

app/views/radiant/admin/preferences/edit.html.haml
- @page_title = @user.name + ' ' + t('preferences') + ' - ' + default_page_title
- body_classes << 'edit_personal_preferences'

- render_region :main do |main|
  - main.edit_header do
    %h1= t('personal_preferences') 

  - main.edit_form do
    - form_for @user, :url => admin_preferences_url, :html => { :method => :put, 'data-onsubmit_status' => "#{t('saving_preferences')}&#8230;" } do |f|
      
      = render :partial => 'radiant/admin/users/avatar'
      
      = render_region :form_top, :locals => {:f => f}
      
      - render_region :form, :locals => {:f => f} do |form|
        - form.edit_name do
          %p
            = f.label :name, t("name")
            = f.text_field :name, :class => "textbox activate", :size => 32, :maxlength => 100 
        
        - form.edit_email do
          %p
            = f.label :email,  t("email_address"), :class => "optional"
            = f.text_field "email", :class => 'textbox', :size => 32, :maxlength => 255
        
        - form.edit_username do
          %p
            = f.label :login, t("username")
            = f.text_field "login", :class => "textbox", :size => 32, :maxlength => 40
        
        - form.edit_password do
          = render "radiant/admin/users/password_fields", :f => f        
        
        - form.edit_locale do
          %p
            = f.label :locale, t('language') 
            = f.select "locale", available_locales_select
      
      - render_region :form_bottom, :locals => {:f => f} do |form_bottom|
        - form_bottom.edit_buttons do
          .buttons
            = save_model_button @user
            = t('or')
            = link_to t('cancel'), admin_url