config/routes.rb
Radiant::Engine.routes.draw do
  namespace :admin do
    resources :pages do
      resources :children, controller: 'pages'
      member do
        get :remove
        post :preview
        put :preview
      end
    end
    resources :layouts do
      member do
        get :remove
      end
    end
    resources :users do
      member do
        get :remove
      end
    end

    resource :preferences
    resource :configuration
    resources :extensions,  only: :index
    resources :page_parts,  only: :create
    resources :page_fields, only: :create
    get 'reference/:type(.:format)' => 'radiant/references#show', as: :reference
  end

  get 'admin' => 'admin/welcome#index', as: :admin
  get 'admin/welcome' => 'admin/welcome#index', as: :welcome
  match 'admin/login' => 'admin/welcome#login', as: :login, via: [:get, :post]
  get 'admin/logout' => 'admin/welcome#logout', as: :logout

  root to: 'site#show_page'

  get 'error/404' => 'site#not_found', as: :not_found
  get 'error/500' => 'site#error', as: :error

  # main catch-all route
  get '*url' => 'site#show_page'
end

app/views/radiant/admin/pages/_fields.html.haml
- include_javascript 'admin/page_preview'
= fields.hidden_field :lock_version
= fields.hidden_field :parent_id
= fields.hidden_field :class_name

= render_region :form_top, :locals => {:f => fields}

- render_region :form, :locals => {:f => fields} do |form|
  - form.edit_title do
    %p.title
      %label{:for=>"page_title"}= t('page_title')
      = fields.text_field :title, :class => 'textbox', :maxlength => 255
  - form.edit_extended_metadata do
    .drawer
      .drawer_contents#attributes
        %table.fieldset
          = render :partial => "meta_row", :collection => @meta, :locals => {:f => fields}
          = render :partial => 'radiant/admin/page_fields/page_field', :collection => @page.fields
          = render_region :extended_metadata, :locals => {:f => fields}
      .drawer_handle
        %a.toggle{:href=>'#attributes', :rel=>"toggle[attributes]", :class=>"#{(meta_errors? ? 'less' : 'more')}"}= meta_label
  - form.edit_page_parts do
    #tab_control
      #tabs.tabs
        #tab_toolbar
          %a.popup{:href=> '#add_part_popup', :title=>t('add_part')}
            = image('add_tab', :alt=>t('add_part'), :title=>"")
      #pages.pages
        = render :partial => 'radiant/admin/page_parts/page_part', :collection => @page.parts
    = render_region :parts_bottom, :locals => {:f => fields}

.set
  - render_region :layout, :locals => {:f => fields} do |layout|
    - layout.edit_layout do
      %p
        = fields.label :layout_id, t('layout')
        = fields.select :layout_id, [[t('select.inherit') , '']] + Layout.all.map { |s| [s.name, s.id] }
    - layout.edit_type do
      %p
        = fields.label :class_name, t('page_type')
        = fields.select :class_name, [[t('select.normal'), '']] + Page.descendants.map { |p| [p.display_name, p.name] }.sort_by { |p| p.first }
    - layout.edit_status do
      %p
        = fields.label :status_id, t('status')
        = fields.select :status_id, status_to_display
    - layout.edit_published_at do
      %p#published_at{:class => (@page.published? ? nil : 'hidden')}
        = fields.label :published_at, t('published_on')
        = fields.text_field :published_at, :class=> "date", :value => (@page.published_at? ? I18n.localize(@page.published_at.to_date, :format =>:long) : nil)
    = render_region :layout_row, :locals => {:f => fields}

- render_region :form_bottom, :locals => {:f => fields} do |form_bottom|
  - form_bottom.edit_buttons do
    - @buttons_partials.each do |partial|
      = render :partial => partial, :locals => {:f => fields}
    .buttons{:style=>"clear: left"}
      = save_model_button(@page)
      = save_model_and_continue_editing_button(@page)
      = submit_tag(t('preview', :default => 'Preview'), :class => 'button', :id => 'show-preview')
      = t('or')
      = link_to t('cancel'), admin_pages_url
    #preview_panel.fullcover.grey_out{:style => 'display: none;'}
      %iframe{:id => 'page-preview', :class => 'fullcover', :name => 'page-preview', :src =>  ActionController::Base.relative_url_root.to_s + '/loading-iframe.html', :frameborder => 0, :scrolling => "auto"}
      .preview_tools
        =submit_tag(t('buttons.save_changes'), :class => 'big save_changes')
        =submit_tag(t('buttons.save_and_continue'), :class => 'big save_and_continue', :name => 'continue')
        %span.info
          = t('or')
          =link_to(t('edit_page'),{}, :class => 'cancel')
  - form_bottom.edit_timestamp do
    = updated_stamp @page

app/views/radiant/admin/pages/_meta_row.html.haml
%tr
  %th.label
    %label{:for=>"page_#{meta_row[:field]}"}= t(meta_row[:field])
  %td.field= f.send(meta_row[:type], meta_row[:field], *meta_row[:args])
  %td.actions
    - if meta_row_counter+1 == @meta.size
      - link_to '#add_field_popup', :class=>'popup' do
        = image 'plus_grey', :alt => t('add_field')

app/views/radiant/admin/pages/_node.html.haml
%tr.page{:class =>"level_#{level}#{children_class}#{virtual_class}", :id => "page_#{page.id}"}
  - render_region :node, :locals => {:page => page, :level => level, :simple => simple} do |node|
    - node.title_column do
      %td.name{:style => "padding-left: #{padding_left(level)}px"}
        %span.w1
          - if simple
            = icon
            = node_title
          - else
            != expander(level) + link_to("#{icon} #{node_title}".html_safe, edit_admin_page_url(page), :title => page.path)
            = page_type
            = spinner
    - node.status_column do
      - unless simple
        %td.status
          %span.status{:class => "#{page.status.name.downcase}_status", :title => "#{timestamp(page.published_at) if page.published_at}"}= t(page.status.name.downcase)
    - node.actions_column do
      - unless simple
        %td.actions
          = page.add_child_option
          = page.remove_option

- if expanded
  - page.children.each do |child|
    - child.becomes(child.class_name.constantize) if child.class_name.present?
    = render_node child, :level => level + 1, :simple => simple

app/views/radiant/admin/pages/_popups.html.haml
- content_for :popups do
  #add_part_popup.popup{:style => "display: none"}
    #add_part_busy.busy{:style => "display: none"}= image('spinner.gif', :alt => "")
    .popup_title= t('add_part')
    = form_for([:admin, PagePart.new], :html => { :onsubmit => "addPart(this); return false" }) do |f|
      %p
        %label{:for => 'part_name_field'}= t('name')
        = f.text_field :name, :id => 'part_name_field', :maxlength => 100, :style => "width: 15em", :class => "textbox big"
        = hidden_field_tag 'index', 0, :id => 'page_part_index_field'
      .buttons
        = submit_tag t('add_part'), :id => 'add_part_button', :class => "button"
        = t('or')
        = link_to_function t('cancel'), "$(this).closePopup()", :class=>"cancel"
  #add_field_popup.popup{:style=>"display: none"}
    #add_field_busy.busy{:style=>"display: none"}= image('spinner.gif', :alt => "")
    .popup_title= t('add_field')
    = form_for [:admin, PageField.new], :html => { :onsubmit => "event.stop(); addField(this)" } do |f|
      %p
        %label{:for=>"page_field_name"}= t('name')
        = f.text_field :name, :maxlength=>100, :class=>'textbox big', :style=>"width: 15em"
        = hidden_field_tag 'index', 2, :id=>'page_field_index_field'
        = hidden_field_tag 'page_field_counter', @page.fields.size
      .buttons
        = submit_tag t('add_field'), :class=>'button', :id=>'add_page_field_button'
        = t('or')
        = link_to_function t('cancel'), "$(this).closePopup()", :class=>"cancel"
  = render_region :popups

app/views/radiant/admin/pages/children.html.haml
- models.each do |child|
  = render_node child, :expand => 1, :level => @level + 1

app/views/radiant/admin/pages/edit.html.haml
- @page_title = @page.title + ' - ' + default_page_title

- render_region :main do |main|
  - main.edit_header do
    %h1= t('edit_page')
  - main.edit_form do
    - form_for @page, :url => admin_page_path(@page), :html => {:method => :put, :multipart => true, :id => 'edit_page', 'data-onsubmit_status'=>t('saving_changes')} do |fields|
      = render :partial => "fields", :object => fields
  - main.edit_popups do
    = render :partial => "popups"

- content_for :page_scripts do
  != page_edit_javascripts

app/views/radiant/admin/pages/index.html.haml
- @page_title = t('pages') + ' - ' + default_page_title

.outset
  = render_region :top
  %table.index#pages{:summary=>t('page_hierarchy')}
    %thead
      %tr
        - render_region :sitemap_head do |sitemap_head|
          - sitemap_head.title_column_header do
            %th.name= t('page') 
          - sitemap_head.status_column_header do
            %th.status= t('status')
          - sitemap_head.actions_column_header do
            %th.actions= t('modify')
    %tbody
      - if @homepage
        = render_node @homepage
      - else
        %tr
          %td.empty{:colspan => admin.page.index.node.length}= t('no_pages')
  = render_region :bottom

- unless @homepage
  #actions
    %ul
      %li= link_to image('plus') + ' ' + t("new_homepage"), new_admin_page_path, :class => 'action_button'

app/views/radiant/admin/pages/new.html.haml
- render_region :main do |main|
  - main.edit_header do
    %h1= t('new_page')    
  - main.edit_form do
    - form_for @page, :url => admin_pages_path, :html => {:id => 'new_page', :multipart => true, 'data-onsubmit_status'=>"Creating page&#8230;"} do |f|
      = render :partial => "fields", :object => f
  - main.edit_popups do
    = render :partial => "popups"

- content_for 'page_scripts', page_edit_javascripts

app/views/radiant/admin/pages/remove.html.haml
- pages = @page.children.count > 1 ? t('pages') : t('page')

%h1= t('remove_pages', :pages => pages)

%p= t('text.pages.remove_warning', :pages => pages).html_safe
    
.inset
  %table.index#site_map
    %tbody
      = render_node @page, :simple => true

= form_for [:admin, @page.becomes(Page)], :html => {:method => :delete, 'data-onsubmit_status'=>"Removing pages&#8230;"} do
  .buttons
    %input.button{:type=>"submit", :value => t('delete_pages', :pages => pages) }/
    = t('or')    
    = link_to t('cancel'), admin_pages_url